INSERT INTO USER (ID, CREATED_DATE, MODIFIED_DATE, EMAIL, NAME, PICTURE, ROLE)
VALUES (1, NULL, NULL, 'rodls365@gmail.com', 'k k', 'https://lh3.googleusercontent.com/a/ACg8ocIJlaaWw1AWNBr312Cl0MEfVs4SeGUTkYAP84k09TPkpQ=s96-c', 'GUEST');
